name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  PORT: 3000
  DATABASE_URL: 'postgresql://postgres:postgres@127.0.0.1:5432/service-ticket-api'
  DATABASE_URL_TEST: 'postgresql://postgres:postgres@127.0.0.1:5432/service-ticket-api-test'
  CRON_SECRET: 'e2e-cron-secret'
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  ci:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run prisma generate && yarn run build

      - name: Run tests
        run: yarn test:ci
